name: Create Snowflake Database

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  create-database:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Snowflake connector
        run: pip install snowflake-connector-python

      - name: Create Snowflake database
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          python -c "
import snowflake.connector
conn = snowflake.connector.connect(
    user='${{ secrets.SNOWFLAKE_USER }}',
    password='${{ secrets.SNOWFLAKE_PASSWORD }}',
    account='${{ secrets.SNOWFLAKE_ACCOUNT }}',
    role='${{ secrets.SNOWFLAKE_ROLE }}',
    warehouse='${{ secrets.SNOWFLAKE_WAREHOUSE }}'
)
cs = conn.cursor()
try:
    cs.execute('CREATE DATABASE IF NOT EXISTS ajay')
    print('Database ajay created successfully.')
finally:
    cs.close()
    conn.close()
"
